version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest
        environment:
          TEST_PG_HOST: 127.0.0.1
          TEST_PG_PORT: 5432
          TEST_PG_USER: postgres
          TEST_PG_DATABASE: pyg_test
      
      - image: circleci/postgres:9.6.2-alpine
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: pyg_test

    working_directory: ~/workspace

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run:
          name: INSTALL DEPENDENCIES
          command: yarn install

      - run:
          name: INSTALL PG CLIENT
          command: sudo apt install -y postgresql-client || true

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: TEST
          command: yarn test

      - run:
          name: UPLOAD COVERAGE
          command: yarn test:cov
